### ISSUE TITLE
OS X EL CAPITAN SUPPORT !!! ??  

### ISSUE THREAD

**Issue by karan16000** [integralpro/nosleep#13]
i Really Need Nosleep on my mac os x 10.11 please update it so that i can install latest update of mac

**Comment by eflyjason** [comment]
yes I want to use it on El Capitan too!

**Comment by mag01** [comment]
Works for me at El Cap. Did you even try?

**Comment by mele113** [comment]
Works for me as well, no issues

**Comment by eflyjason** [comment]
Works fine here

**Comment by IdanAdar** [comment]
The Lock Screen option does not work in El Capitan.

**Comment by karan16000** [comment]
Yeahh all working except lockscreen  :)

**Comment by xjlin0** [comment]
When I close the lid, El Captain still make my MBP sleep.....

**Comment by carn1x** [comment]
Not working on El Capitan for me. I have a KVM connected to MBP with the lid closed. Switch the KVM to the other machine and attempt to query the MBP and it works for a short while before going unresponsive. Switch KVM back to MBP and get a black screen which awakes on input to the default lock screen
