### ISSUE TITLE
[OS X 10.11] The session is not locked when the lid is closed

### ISSUE THREAD

**Issue by magicgoose** [integralpro/nosleep#14]
In other words, the option "Require password on display opening" has no effect.

This is a big deal, because it's easy for one to forget to manually lock screen after they got used to old behavior. And forgetting to lock screen sometimes can be disastrous.

**Comment by magicgoose** [comment]
Probably related to https://github.com/integralpro/nosleep/issues/9

**Comment by CoreISP** [comment]
Yeah, the lock isn't working unfortunately. This is, however, quite an important feature.

**Comment by mele113** [comment]
Manually Locking Sceen selection does not work in ElCapitan. I Switched to InsomniaX...http://semaja2.net

**Comment by magicgoose** [comment]
@mele113 hmm, looks interesting!
is it open-source?

**Comment by mele113** [comment]
Free from..http://semaja2.net/projects/insomniaxinfo/
Sent from iCloud

On Oct 25, 2015, at 04:54 PM, magicgoose <notifications@github.com> wrote:

@mele113 hmm, looks interesting!
is it open-source?

**Comment by integralpro** [comment]
Should work in 1.5.0
