### ISSUE TITLE
NoSleep in CLI?

### ISSUE THREAD

**Issue by antonbrams** [integralpro/nosleep#15]
Hi, guys!

Sorry for potential offtop,

but i can't find any tutorial for using this awesome tool in terminal. Is it possible?
Can anybody show me some howto or tutorial page for installing and using with commandline?

Thanks!

**Comment by brablc** [comment]
I do not know about manual, but here is my script which uses it. May be it would help? https://github.com/brablc/clit/blob/master/tmutil-safe-nas-backup

**Comment by integralpro** [comment]
Thanks for answering to the questions!
