### ISSUE TITLE
Screensaver does not start if the notebook is closed and nonsleep is active

### ISSUE THREAD

**Issue by jjconti** [integralpro/nosleep#18]
Screensaver does not start if the notebook is closed and nonsleep is active. It should as is a valid use case.

**Comment by Chip-McK** [comment]
I use "Hot Corners" in this scenario and the two work flawlessly together

**Comment by jjconti** [comment]
Yes... but you have to connect a mouse to activate it.

**Comment by Chip-McK** [comment]
On my laptop, NoSleep does not prevent the ScreenSaver from activating/starting.

**Comment by 1-61803** [comment]
On v1.3.3 I have `Require password on display opening` enabled and closing the lid starts the screen saver. It shouldn't. Some screen savers are CPU intensive and drain your battery. Not good. It seems `NoSleep` is not being maintained anymore.

**Comment by Chip-McK** [comment]
Current release is v1.4.0

**Comment by 1-61803** [comment]
I remember having some trouble with v1.4.0. Does the screen saver start when closing the lid in that version too?

**Comment by integralpro** [comment]
1.5.0
