### ISSUE TITLE
Disable NoSleep on exit.

### ISSUE THREAD

**Issue by arjunmayilvaganan** [integralpro/nosleep#24]
I think it would reasonable to have NoSleep disable itself on exit. I quit NoSleep, but it was still enabled and did not realise it. The charge was draining quickly and then it struck me. Any reasons to disagree?

**Comment by markcoker** [comment]
+1

**Comment by arjunmayilvaganan** [comment]
This issue is being closed due to inactivity. Please feel to re-open.

The last commit to the repo was on June '15. Repo no longer seems maintained.
