### ISSUE TITLE
Can't single click menubar icon to start

### ISSUE THREAD

**Issue by andrewhamon** [integralpro/nosleep#3]
On an older version, I could simply click the menu bar icon to enable NoSleep. On the current version, this is no longer possible (clicking the icon brings up a menu from which I can then select "Enable NoSleep").

**Comment by alexlouden** [comment]
+1

**Comment by alexlouden** [comment]
FYI the old version is available to download here: https://code.google.com/p/macosx-nosleep-extension/downloads/detail?name=NoSleep-1.3.3.dmg&can=1&q=

**Comment by KenPowers** [comment]
Yeah, I wound up doing that. I downloaded the new version to use the uninstaller then I downloaded the old version and installed it.

**Comment by aivas** [comment]
Павел, верните включение режима по клике по иконке. И иконка ранее было намного красивее, чем текущая в версии 1.4.0

**Comment by benmarten** [comment]
+1
Looks like this feature was intentionally removed by Pavel!
As a quickfix, i simply cloned the repo and reverted until before the commit where he removed the single click (da9b8ce95ec453dbdb81e8f912c500b11fc87f62)
I've then exported the file, you can just use this one for now: https://dl.dropboxusercontent.com/u/68092546/NoSleep.zip

I tried to update but I couldn't solve some build errors, this project is kind of legacy. Probably needs a complete restart :P

**Comment by integralpro** [comment]
It's back in 1.5.0
