### ISSUE TITLE
10.13 High Sierra Kernel Extension is not loaded

### ISSUE THREAD

**Issue by entrion** [integralpro/nosleep#31]
Fresh install of High Sierra on 15 MBPR

Oops!

NoSleep Kernel Extension is not loaded. 

On both install and app launch.

**Comment by sup2069** [comment]
Same issue.

OS: High Sierra
NoSleep: 1.4.0

**Comment by formvoltron** [comment]
same issue.  darn I really liked no sleep!

**Comment by formvoltron** [comment]
schaweet! thanks!

**Comment by integralpro** [comment]
Yep, it's may be outdated these days. Anyway, thanks for questions and answers!
BTW, try 1.5.0
