### ISSUE TITLE
2 icons in tray after installing 1.5.0

### ISSUE THREAD

**Issue by hellysmile** [integralpro/nosleep#36]
I've used script to uninstall 1.4.0, afterwards copied NoSleep to utilities
After reboot 2 icons at tray
If I uncheck "Start in startup" and reboot only 1 icon persists, but it still somehow autostarts

**Comment by conioh** [comment]
Similar problem here.

**Comment by AntonioStipic** [comment]
Same problem here

**Comment by chris400** [comment]
same here

**Comment by arieladar** [comment]
I used **CCleaner for Mac → Tools → Startup** to remove the redundant entry.
I left one classified as a **Service** rather than an **Application**. Not sure whether or not that is the desired classification though...

**Comment by kevdogg** [comment]
I unfortunately have same issue with the two startup icons

**Comment by chris400** [comment]
> I used **CCleaner for Mac → Tools → Startup** to remove the redundant entry.
> I left one classified as a **Service** rather than an **Application**. Not sure whether or not that is the desired classification though...

I did the same to fix it.

**Comment by integralpro** [comment]
Please uninstall previous version, using the script from the DMG.

**Comment by Calorion** [comment]
I downloaded 1.5.1. I uninstalled it with Uninstall.command. I dragged the icon to Utilities, opened it, and restarted. I still have two icons in the menu bar.

macOS 10.13.6.
