### ISSUE TITLE
v1.5.0 doesn't work on Sierra(10.12.6)

### ISSUE THREAD

**Issue by Bonzenfighter** [integralpro/nosleep#40]
The update window tells the user to update to v1.5.0, which "adds OS X 10.13 Support, plus minor stuff", without telling one that it doesn't support your current version(or maybe every OSX <10.13?). Thus, you have to manually install v1.4.0 again (and probably never update again?).

**Comment by MiMoHo** [comment]
I'm having the same issue. Information on system requirements along with support for 10.11+ would be favourable.

**Comment by kfjelsted** [comment]
I get an error that "Kernel extension not loaded" on Mojave!

**Comment by LoganDark** [comment]
@kfjelsted use 1.4.0
![image](https://user-images.githubusercontent.com/4723091/50569594-9e25c980-0d1d-11e9-92f2-d0873bd31596.png)

**Comment by integralpro** [comment]
Sorry about that, please use 1.4.0 for old OS versions.

**Comment by LoganDark** [comment]
@integralpro and new ones...
