### ISSUE TITLE
OS X 10.11 - Lock Screen does not work

### ISSUE THREAD

**Issue by ghost** [integralpro/nosleep#9]
The lock screen button does not work in OS X 10.11 Developer Beta 1

**Comment by Mangosteen-Yang** [comment]
This problem also happen in public beta2.

**Comment by Mangosteen-Yang** [comment]
I just updated it to 1.4.0
It can be worked.
my os is :10.11 pb2

**Comment by bric3** [comment]
Working with 
1.11 Public Beta 4 (15A243d)
NoSleep 1.4

**Comment by computeronix** [comment]
Interesting running the 10.11 GM (15A282b) NoSleep 1.4  (fresh install of OS and app)
Lock screen will not work - click it and nothing happens

Currently using the Key Chain utility -> lock screen and works fine.

Anyone else try on GM?

**Comment by Mangosteen-Yang** [comment]
My GM with 1.4 is works well.

**Comment by computeronix** [comment]
Hmm. Guess  it is just me. May try a reinstall of the app again and cross fingers :)

Sent from my iPhone

On Sep 15, 2015, at 8:54 AM, Mangosteen <notifications@github.com<mailto:notifications@github.com>> wrote:

My GM with 1.4 is works well.
> ? 2015?9?15????8:52?Bill McIlhargey <notifications@github.com<mailto:notifications@github.com>> ???
>
> Interesting running the 10.11 GM (15A282b) NoSleep 1.4 (fresh install of OS and app)
> Lock screen will not work - click it and nothing happens
>
> Currently using the Key Chain utility -> lock screen and works fine.
>
> Anyone else try on GM?
>
> -
> Reply to this email directly or view it on GitHub <https://github.com/integralpro/nosleep/issues/9#issuecomment-140378741>.
>


-

**Comment by seadog007** [comment]
I can't disable NoSleep, if I do that and close my screen, then the system crash.........

**Comment by ainstushar** [comment]
Didn't El Cap change the way it handles Kernel extensions? KEXT bypassing is gone now. That combined with SIP means that El Cap will refuse to load any kernel extensions that aren’t signed by a valid Apple developer ID.

More info at: http://apple.stackexchange.com/questions/191421/can-i-make-my-own-kernel-extensions-on-el-capitan and https://developer.apple.com/support/code-signing/

Whether or not NoSleep will be affected or not, I don't know. Are you guys saying it will work? I am a bit hesitant to update since this app is so damn good.

**Comment by integralpro** [comment]
Will try to find some time to look at el capitan. Thanks for feedbacks.

--Pavel

**Comment by ohnx** [comment]
For me at least (I'm running El Cap on a MacBook Air), the latest release works in the sense that it prevents the laptop from sleeping.

However, Lock Screen doesn't work.

**Comment by Xenocide93** [comment]
Macbook Pro 13 Retina (2015) running 10.11 El Capitan also have to same problem. It does not ask for password when open the lid. Right click on the icon and choose "Lock Screen" also does nothing.

Thanks for the App, by the way. Solve many problem : )

**Comment by HassanAlthaf** [comment]
Doesn't work for me either.

**Comment by integralpro** [comment]
Sorry for not uploading the fix, but it should work in 1.5.0:)
